# User config
author: "Honghanh"
tagline: "Dịch vụ cưới"
description: "Trang website dự kiến sẽ được hoàn thành vào ngày 27/03/2023. Hy vọng sẽ mang đến trải nghiệm tốt nhất cho quý khách hàng."
keywords: "Wedding invitation"
email: "duongnguyen.22@icloud.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed